openapi: 3.0.0
info:
  title: AI Resume Writer 인증 API
  version: 1.0.0

servers:
  - url: http://localhost:8000/api

paths:
  /register:
    post:
      summary: 회원가입
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                      refresh_token:
                        type: string
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                          email:
                            type: string
        '400':
          description: 실패(잘못된 형식)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /token:
    post:
      summary: 토큰발급(로그인)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  example: secure_password123
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
                      refresh_token:
                        type: string
                        example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: John Doe
                          email:
                            type: string
                            format: email
                            example: user@example.com
        '400':
          description: 실패(필수 필드 누락)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "이메일과 비밀번호가 필요합니다."
        '401':
          description: 실패(잘못된 자격 증명)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "잘못된 이메일 또는 비밀번호입니다."
        '403':
          description: 실패(비활성화된 계정)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "계정이 비활성화되어 있습니다."

  /google-login:
    post:
      summary: Google 로그인/회원가입
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: 4/0AX4XfWg8...
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
                      refresh_token:
                        type: string
                        example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: John Doe
                          email:
                            type: string
                            format: email
                            example: user@example.com
        '400':
          description: 실패(인증 코드 누락)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "인증 코드가 필요합니다."
        '401':
          description: 실패(인증 실패)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Google 인증 실패"

  /logout/:
    post:
      summary: 로그아웃
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  description: Refresh Token (선택적)
                  example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "로그아웃되었습니다."
        '500':
          description: 실패(서버 오류)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "서버 오류가 발생했습니다."

  /token/refresh/:
    post:
      summary: Access Token 재발급
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
                  description: Refresh Token
                  example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
        '401':
          description: 실패(유효하지 않은 Refresh Token)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "유효하지 않은 Refresh Token입니다."
        '400':
          description: 실패(필수 필드 누락)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Refresh Token이 필요합니다."

  /update-profile/:
    put:
      summary: 프로필 수정
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  nullable: true
                  description: 변경할 사용자 이름 (변경하지 않을 경우 생략 가능)
                  example: 홍길동
                current_password:
                  type: string
                  description: 현재 비밀번호 (필수)
                  example: current_password123
                password:
                  type: string
                  nullable: true
                  description: 변경할 새 비밀번호 (변경하지 않을 경우 생략 가능)
                  example: new_password456
              required:
                - current_password
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                      message:
                        type: string
                        example: "프로필이 성공적으로 업데이트되었습니다."
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          email:
                            type: string
                            format: email
                            example: user@example.com
                          name:
                            type: string
                            example: 홍길동
                  - type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                      message:
                        type: string
                        example: "비밀번호가 성공적으로 변경되었습니다."
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          email:
                            type: string
                            format: email
                            example: user@example.com
                          name:
                            type: string
                            example: 홍길동
                  - type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                      message:
                        type: string
                        example: "비밀번호와 프로필이 성공적으로 업데이트되었습니다."
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          email:
                            type: string
                            format: email
                            example: user@example.com
                          name:
                            type: string
                            example: 홍길동
        '400':
          description: |
            실패
            - 현재 비밀번호를 입력해주세요.
            - 유효하지 않은 데이터
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "현재 비밀번호를 입력해주세요."
                  errors:
                    type: object
                    nullable: true
                    example:
                      name: ["이 필드는 blank일 수 없습니다."]
        '401':
          description: 실패(인증 실패)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "현재 비밀번호가 일치하지 않습니다."
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "프로필 업데이트 중 오류가 발생했습니다."